import type { PdfDoc } from "./types";

export const PDFS: PdfDoc[] = [
  {
    id: "major-1-syllabus",
    title: "Major Paper I — Fundamentals of Botany",
    titleHi: "मेजर पेपर I — बॉटनी के मूल सिद्धांत",
    group: "major-syllabus",
    file: "/pdfs/major-1-syllabus.pdf",
    pagesHint: "Theory + practical syllabus scan",
  },
  {
    id: "major-2-syllabus",
    title: "Major Paper II — Microbes and Lower Plant Diversity",
    titleHi: "मेजर पेपर II — सूक्ष्मजीव एवं निम्न पादप विविधता",
    group: "major-syllabus",
    file: "/pdfs/major-2-syllabus.pdf",
    pagesHint: "Original uploaded syllabus · 2025–26",
  },
  {
    id: "major-3-syllabus",
    title: "Major Paper III — Applied Botany",
    titleHi: "मेजर पेपर III — व्यावहारिक बॉटनी",
    group: "major-syllabus",
    file: "/pdfs/major-3-syllabus.pdf",
    pagesHint: "Original uploaded syllabus · 2025–26",
  },
  {
    id: "minor-1-syllabus",
    title: "Minor Paper I — Elementary Botany",
    titleHi: "माइनर पेपर I — प्रारंभिक बॉटनी",
    group: "minor-syllabus",
    file: "/pdfs/minor-1-syllabus.pdf",
    pagesHint: "Original uploaded syllabus · 2025–26",
  },
  {
    id: "minor-2-syllabus",
    title: "Minor Paper II — Diversity of Plants",
    titleHi: "माइनर पेपर II — पादप विविधता",
    group: "minor-syllabus",
    file: "/pdfs/minor-2-syllabus.pdf",
    pagesHint: "Original uploaded syllabus · 2025–26",
  },
  {
    id: "major-1-unit-1-notes",
    title: "Major I · Unit I notes",
    titleHi: "मेजर I · यूनिट I नोट्स",
    group: "major-notes",
    file: "/pdfs/major-1-unit-1-notes.pdf",
    pagesHint: "Unit-wise class notes",
  },
  {
    id: "major-1-unit-2-notes",
    title: "Major I · Unit II notes",
    titleHi: "मेजर I · यूनिट II नोट्स",
    group: "major-notes",
    file: "/pdfs/major-1-unit-2-notes.pdf",
    pagesHint: "Unit-wise class notes",
  },
  {
    id: "major-1-unit-3-notes",
    title: "Major I · Unit III notes",
    titleHi: "मेजर I · यूनिट III नोट्स",
    group: "major-notes",
    file: "/pdfs/major-1-unit-3-notes.pdf",
    pagesHint: "Unit-wise class notes",
  },
  {
    id: "major-1-unit-4-notes",
    title: "Major I · Unit IV notes",
    titleHi: "मेजर I · यूनिट IV नोट्स",
    group: "major-notes",
    file: "/pdfs/major-1-unit-4-notes.pdf",
    pagesHint: "Unit-wise class notes",
  },
  {
    id: "major-1-unit-5-notes",
    title: "Major I · Unit V notes",
    titleHi: "मेजर I · यूनिट V नोट्स",
    group: "major-notes",
    file: "/pdfs/major-1-unit-5-notes.pdf",
    pagesHint: "Pages 11–12 of class notes",
  },
  {
    id: "major-1-complete-notes",
    title: "Major I · Complete notes PDF",
    titleHi: "मेजर I · संपूर्ण नोट्स PDF",
    group: "major-notes",
    file: "/pdfs/major-1-complete-notes.pdf",
    pagesHint: "Combined Major Paper I notes",
  },
];
